global:
  environment: staging
  namespace: yas-staging
  domainName: storefront-staging.yas.local

services:
  storefront:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-storefront
      tag: v1.0.0
    ingress:
      enabled: true
      host: storefront-staging.yas.local

  backoffice:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-backoffice
      tag: v1.0.0
    ingress:
      enabled: true
      host: backoffice-staging.yas.local

  storefront-bff:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-storefront-bff
      tag: v1.0.0

  backoffice-bff:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-backoffice-bff
      tag: v1.0.0

  product:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-product
      tag: v1.0.0

  media:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-media
      tag: v1.0.0

  cart:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-cart
      tag: v1.0.0

  order:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-order
      tag: v1.0.0

  customer:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-customer
      tag: v1.0.0

  inventory:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-inventory
      tag: v1.0.0

  tax:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-tax
      tag: v1.0.0

  search:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-search
      tag: v1.0.0

  sampledata:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-sampledata
      tag: v1.0.0

  swagger-ui:
    enabled: true
    image:
      repository: docker.io/luongtrz/yas-swagger-ui
      tag: v1.0.0

  # Non-baseline services — disabled
  rating:
    enabled: false
  location:
    enabled: false
  promotion:
    enabled: false
  payment:
    enabled: false
  payment-paypal:
    enabled: false
  recommendation:
    enabled: false
  webhook:
    enabled: false
