global:
  environment: staging
  namespace: yas-staging
  domainName: storefront-staging.yas.local

services:
  storefront:
    enabled: true
    schedulingProfile: ui-on-master
    image:
      repository: luongtrz/yas-storefront
      tag: v1.0.0
    service:
      nodePort: 32083
    ingress:
      enabled: true
      host: storefront-staging.yas.local
  backoffice:
    enabled: true
    schedulingProfile: ui-on-master
    image:
      repository: luongtrz/yas-backoffice
      tag: v1.0.0
    service:
      nodePort: 32084
    ingress:
      enabled: true
      host: backoffice-staging.yas.local
  storefront-bff:
    enabled: true
    image:
      repository: luongtrz/yas-storefront-bff
      tag: v1.0.0
  backoffice-bff:
    enabled: true
    image:
      repository: luongtrz/yas-backoffice-bff
      tag: v1.0.0
  product:
    enabled: true
    image:
      repository: luongtrz/yas-product
      tag: v1.0.0
  media:
    enabled: true
    image:
      repository: luongtrz/yas-media
      tag: v1.0.0
  cart:
    enabled: true
    image:
      repository: luongtrz/yas-cart
      tag: v1.0.0
  customer:
    enabled: true
    image:
      repository: luongtrz/yas-customer
      tag: v1.0.0
  rating:
    enabled: false
  location:
    enabled: false
  order:
    enabled: true
    image:
      repository: luongtrz/yas-order
      tag: v1.0.0
  inventory:
    enabled: true
    image:
      repository: luongtrz/yas-inventory
      tag: v1.0.0
  tax:
    enabled: true
    image:
      repository: luongtrz/yas-tax
      tag: v1.0.0
  search:
    enabled: true
    image:
      repository: luongtrz/yas-search
      tag: v1.0.0
  promotion:
    enabled: false
  payment:
    enabled: false
  payment-paypal:
    enabled: false
  recommendation:
    enabled: false
  sampledata:
    enabled: true
    replicaCount: 0
    image:
      repository: luongtrz/yas-sampledata
      tag: v1.0.0
  swagger-ui:
    enabled: true
    schedulingProfile: ui-on-master
    image:
      repository: luongtrz/yas-swagger-ui
      tag: v1.0.0
    service:
      nodePort: 32085
    ingress:
      enabled: true
      host: swagger-ui-staging.yas.local
  webhook:
    enabled: false
