global:
  environment: dev
  namespace: yas-dev
  domainName: storefront-dev.yas.local

services:
  storefront:
    schedulingProfile: ui-on-master
    ingress:
      enabled: true
      host: storefront-dev.yas.local
  backoffice:
    schedulingProfile: ui-on-master
    ingress:
      enabled: true
      host: backoffice-dev.yas.local
  sampledata:
    replicaCount: 0
  swagger-ui:
    schedulingProfile: ui-on-master
