global:
  environment: dev
  namespace: yas-dev
  domainName: storefront-dev.yas.local

services:
  storefront:
    ingress:
      enabled: true
      host: storefront-dev.yas.local
  backoffice:
    ingress:
      enabled: true
      host: backoffice-dev.yas.local

